config/routes.rb
ConverterInn::Application.routes.draw do
  root 'home#index'
  post 'parse' => 'home#parse'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def parse
    allinn = params[:form][:inn]
    @results_string = ["№/УНП/Название/Статус"]
    @all_stat = 0
    @good_stat = 0
    @bad_stat = 0
    @other_stat = 0
    @error_stat = 0
    string_index = 1
    allinn.split("\r\n").each do |inn|
      begin
        url = "http://www.portal.nalog.gov.by/grp/getData?unp=#{inn}&charset=UTF-8"
        response = HTTParty.get(url, format: :xml)
        inn_c = Hash.from_xml(response.body)["ROWSET"]["ROW"]["VUNP"]
        stat_c = Hash.from_xml(response.body)["ROWSET"]["ROW"]["VKODS"]
        name_c = Hash.from_xml(response.body)["ROWSET"]["ROW"]["VNAIMK"]
        @results_string.push(string_index.to_s + "/" + inn_c + "/" + name_c + "/" + stat_c)
        string_index += 1
        @all_stat += 1
        if stat_c == "Действующий"
          @good_stat += 1
        elsif stat_c == "Ликвидирован" or "В стадии ликвидации"
          @bad_stat += 1
        else
          @other_stat += 1
        end
      rescue NoMethodError
        @results_string.push(string_index.to_s + "/" + inn.to_s + "/ /Ошибка")
        string_index += 1
        @all_stat += 1
        @error_stat += 1
        next
      end
    end
    render :index
  end
end

# Для тестов
# 191111259
# 101179571
# 190837422
# 190909930
# 191063786
# 192381206
# 191113330
# 190700600
# 101251041
# 806000181
# 806000258
# 806000299
# 806000311
# 806000393
# 806000429
# 806000431
# 806000508
# 806000510
# 806000536
# 806000549
# 806000551
# 806000564
# 806000577
# 806000592
# 806000602
# 806000615
# 806000628
# 806000630

# 190436848
# 100063699
# 190735914
# 790916191
# 123456789
# 290505026
# 192456501
# 192369430
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% provide(:title, 'Cloud check')%>


<% if @results_string.to_a.length == 0 %>
  <div class="well">
    <div class="row justify-content-center">
      <p class="h1 center">Введите УНП</p>
    </div>
    <%= form_for(:form, url: parse_path) do |f| %>
      <%= f.text_area :inn, size: "30x3", placeholder: "123456789
234567890"%><br />
      <p> </p>
      <%= f.submit "Искать!", class: "btn btn-primary outline"%>
    <% end %>
  </div>
<% else %>
  <div class="container">
    <div class="well">
      <h1>Всего проверено : <%= @all_stat %></h1>
      <% unless @error_stat == 0 %>
        <p style="color:red;"><b>В одном из значений ошибка!</b></p>
      <% end %>
      <%= pie_chart({"Действующий" => @good_stat, "Ликвидирован / в процессе ликвидации" => @bad_stat,
               "В другом статусе" => @other_stat, "Ошибка в значении" => @error_stat}, donut: true, legend: "right") %>
    </div>
    <div class="well">
      <% @results_string.each do |result| %>
        <div class="row justify-content-center">
          <div class="col-1 border border-success">
            <%= result.split("/")[0] %>
          </div>
          <div class="col border border-success">
            <%= result.split("/")[1] %>
          </div>
          <div class="col-5 border border-success">
            <%= result.split("/")[2] %>
          </div>
          <div class="col border border-success">
            <% if result.split("/")[3] == "Действующий" %>
              <%= result.split("/")[3] %>
            <% elsif result.split("/")[3] == "Статус" %>
              <%= result.split("/")[3] %>
            <% else %>
              <b style="color:orange;"><%= result.split("/")[3] %></b>
            <% end %>
          </div>
        </div>
      <% end %>
      <p> </p>
      <a href="/" class="btn btn-primary outline" role="button" aria-pressed="true">Еще раз!</a>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link href="starter-template.css" rel="stylesheet">
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      .btn-main{
      background-color:#32A77B;
      color:white;
      }
      div.b {
        border: 1px solid black;
        outline-style: solid;
        outline-color: coral;
      }
      .btn {
          padding: 14px 24px;
          border: 0 none;
          font-weight: 700;
          letter-spacing: 1px;
          text-transform: uppercase;
      }

      .btn:focus, .btn:active:focus, .btn.active:focus {
          outline: 0 none;
      }

      .btn-primary {
          background: #0099cc;
          color: #ffffff;
      }

      .btn-primary:hover, .btn-primary:focus, .btn-primary:active, .btn-primary.active, .open > .dropdown-toggle.btn-primary {
          background: #33a6cc;
      }

      .btn-primary:active, .btn-primary.active {
          background: #007299;
          box-shadow: none;
      }
      .btn.outline {
        background: none;
        padding: 12px 22px;
      }
      .btn-primary.outline {
        border: 2px solid #32A77B;
        color: #32A77B;
      }
      .btn-primary.outline:hover, .btn-primary.outline:focus, .btn-primary.outline:active, .btn-primary.outline.active, .open > .dropdown-toggle.btn-primary {
        color: #000000;
        border-color: #000000;
      }
      .btn-primary.outline:active, .btn-primary.outline.active {
        border-color: #32A77B;
        color: #32A77B;
        box-shadow: none;
      }
    </style>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color: #32A77B;">
      <a class="navbar-brand" href="/">Cloud check</a>
    </nav>
    <main role="main" class="container text-center">
      <div class="starter-template">
        <%= yield %>
      </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
  </body>
</html>